name: Build Boot Image

on:
  workflow_dispatch:
    inputs:
      kernel_version:
        description: 'Kernel version (e.g., 6.18)'
        required: true
        default: '6.18'
        type: string
      distribution:
        description: 'Distribution (ubuntu)'
        required: true
        default: 'ubuntu'
        type: string
      release_tag:
        description: 'Release tag for GitHub release'
        required: true
        default: 'v1.0.0'
        type: string

env:
  KERNEL_VERSION: ${{ github.event.inputs.kernel_version }}
  DISTRIBUTION: ${{ github.event.inputs.distribution }}
  RELEASE_TAG: ${{ github.event.inputs.release_tag }}

jobs:
  build-boot-image:
    name: Build Boot Image
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget util-linux e2fsprogs
        
    - name: Download rootfs image
      run: |
        ROOTFS_URL="https://github.com/${{ github.repository }}/releases/download/${{ env.RELEASE_TAG }}/root-${{ env.DISTRIBUTION }}-${{ env.KERNEL_VERSION }}.img"
        wget -O rootfs.img "$ROOTFS_URL"
        
    - name: Verify rootfs image
      run: |
        if [[ ! -f "rootfs.img" ]]; then
          echo "Rootfs image not found"
          exit 1
        fi
        
        ROOTFS_SIZE=$(stat -c%s "rootfs.img" 2>/dev/null || stat -f%z "rootfs.img" 2>/dev/null)
        if [[ $ROOTFS_SIZE -eq 0 ]]; then
          echo "Rootfs image is empty"
          exit 1
        fi
        
        echo "Rootfs image verified: $ROOTFS_SIZE bytes"
        
    - name: Build boot image
      run: |
        chmod +x raphael-boot_build.sh
        ./raphael-boot_build.sh \
          --kernel-version "${{ env.KERNEL_VERSION }}" \
          --distribution "${{ env.DISTRIBUTION }}" \
          --rootfs-image "rootfs.img" \
          --output "xiaomi-k20pro-boot-${{ env.DISTRIBUTION }}-${{ env.KERNEL_VERSION }}.img"
        
    - name: Verify boot image
      run: |
        BOOT_FILE="xiaomi-k20pro-boot-${{ env.DISTRIBUTION }}-${{ env.KERNEL_VERSION }}.img"
        
        if [[ ! -f "$BOOT_FILE" ]]; then
          echo "Boot image not created"
          exit 1
        fi
        
        BOOT_SIZE=$(stat -c%s "$BOOT_FILE" 2>/dev/null || stat -f%z "$BOOT_FILE" 2>/dev/null)
        if [[ $BOOT_SIZE -eq 0 ]]; then
          echo "Boot image is empty"
          exit 1
        fi
        
        echo "Boot image verified: $BOOT_SIZE bytes"
        
    - name: Upload boot image to release
      uses: actions/upload-artifact@v4
      with:
        name: boot-image-${{ env.DISTRIBUTION }}-${{ env.KERNEL_VERSION }}
        path: xiaomi-k20pro-boot-${{ env.DISTRIBUTION }}-${{ env.KERNEL_VERSION }}.img
        retention-days: 1
        
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          xiaomi-k20pro-boot-${{ env.DISTRIBUTION }}-${{ env.KERNEL_VERSION }}.img
        tag_name: ${{ env.RELEASE_TAG }}
        name: "Boot Image for Xiaomi K20 Pro (Raphael) - ${{ env.DISTRIBUTION }} ${{ env.KERNEL_VERSION }}"
        body: |
          Boot image for Xiaomi K20 Pro (Raphael) with ${{ env.DISTRIBUTION }} and kernel ${{ env.KERNEL_VERSION }}
          
          ## Usage
          
          1. Download the boot image
          2. Flash to boot partition using fastboot
          3. Reboot device
          
          ## Requirements
          
          - Rootfs image for the same kernel version and distribution
          - Fastboot tools
          - Unlocked bootloader